user_name: "" 
token: ''    # get token and user name at http://113.100.143.90:5000/
leaderboard_id: 0  # 0 if not using any other training strategy , 1 if any
detector : [yolov5]
training_docker: ['youdaoyzbx/ymir-executor:ymir1.1.0-sample-tmi']
mining_algo: [cald]
